import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'tr' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    home: 'Home',
    about: 'About',
    services: 'Services',
    testimonials: 'Testimonials',
    contact: 'Contact',
    
    // Auth
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    phone: 'Phone',
    
    // Countries
    turkey: 'Turkey',
    france: 'France',
    tunisia: 'Tunisia',
    canada: 'Canada',
    
    // Services
    universityAdmission: 'University Admission',
    scholarships: 'Scholarships',
    visaGuidance: 'Visa Guidance',
    accommodation: 'Accommodation',
    
    // Contact
    contactTitle: 'Contact Us',
    sendMessage: 'Send Message',
    subject: 'Subject',
    message: 'Message',
    sendMessageBtn: 'Send Message',
    quickContact: 'Quick Contact',
    chatWhatsApp: 'Chat on WhatsApp',
    ourOffices: 'Our Offices',
    businessHours: 'Business Hours',
    mondayFriday: 'Monday - Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    closed: 'Closed',
    emergencyConsultations: 'Emergency consultations available 24/7',
    available24Hours: 'Available 24/7',
    
    // About
    aboutDescription: 'Your trusted partner in international education, helping students achieve their dreams of studying abroad.',
    
    // Homepage content
    welcomeSubtitle: 'Your gateway to world-class education and unforgettable experiences. Discover opportunities, connect with universities, and start your international journey today.',
    startJourney: 'Start Your Journey',
    getStarted: 'Get Started',
    universities: 'Universities',
    internationalStudents: 'International Students',
    provinces: 'Provinces',
    seasons: 'Seasons',
    everythingAboutTurkey: 'Everything About Turkey',
    allInformationNeeded: 'All the information you need to make informed decisions about your education abroad',
    universitiesAndPrograms: 'Universities & Programs',
    exploreUniversities: 'Explore top universities and academic programs',
    scholarshipsAndFunding: 'Scholarships & Funding',
    turkishScholarships: 'Discover Turkish government and university scholarships',
    citiesAndLifestyle: 'Cities & Lifestyle',
    discoverCities: 'Discover Turkish cities and student life',
    economyAndLivingCosts: 'Economy & Living Costs',
    currentEconomicSituation: 'Current economic situation and cost of living',
    whyTurkey: 'Why Turkey?',
    strategicLocation: 'Strategic Location',
    strategicLocationDesc: 'Bridge between Europe and Asia with rich cultural heritage',
    culturalRichness: 'Cultural Richness',
    culturalRichnessDesc: 'Experience diverse cultures and historical significance',
    hospitality: 'Turkish Hospitality',
    hospitalityDesc: 'Warm welcome and friendly environment for international students',
    easyAccess: 'Easy Access',
    easyAccessDesc: 'Convenient travel connections to Europe, Asia, and Africa',
    startEducationalJourney: 'Start Your Educational Journey Today',
    guideFromApplication: 'We guide you from application to graduation - your success is our mission',
    applyNow: 'Apply Now',
    
    // Services descriptions
    universityAdmissionDesc: 'Complete support for university applications and admissions process.',
    scholarshipsDesc: 'Find and apply for scholarships to fund your education abroad.',
    visaGuidanceDesc: 'Expert assistance with visa applications and documentation.',
    accommodationDesc: 'Help finding suitable housing and accommodation options.',
    
    // Service features
    universitySelection: 'University Selection',
    applicationDocuments: 'Application Documents',
    personalStatement: 'Personal Statement',
    interviewPrep: 'Interview Preparation',
    applicationSubmission: 'Application Submission',
    scholarshipDatabase: 'Scholarship Database',
    eligibilityAssessment: 'Eligibility Assessment',
    applicationAssistance: 'Application Assistance',
    essayWriting: 'Essay Writing',
    financialAid: 'Financial Aid',
    visaConsultation: 'Visa Consultation',
    documentChecklist: 'Document Checklist',
    embassyAppointment: 'Embassy Appointment',
    postArrival: 'Post-Arrival Support',
    universityDorms: 'University Dormitories',
    privateHousing: 'Private Housing',
    rentalAgreement: 'Rental Agreement',
    areaRecommendations: 'Area Recommendations',
    moveInSupport: 'Move-in Support',
    
    // Process
    ourProcess: 'Our Process',
    simpleStepByStep: 'Simple step-by-step process to get you started',
    initialConsultation: 'Initial Consultation',
    initialConsultationDesc: 'Free consultation to understand your goals and preferences',
    personalizedPlan: 'Personalized Plan',
    personalizedPlanDesc: 'Custom roadmap tailored to your academic and career objectives',
    applicationSupport: 'Application Support',
    applicationSupportDesc: 'End-to-end assistance with applications and documentation',
    successBeyond: 'Success & Beyond',
    successBeyondDesc: 'Ongoing support even after you start your studies abroad',
    
    // General
    ourServices: 'Our Services',
    comprehensiveSupport: 'Comprehensive support for your international education journey',
    learnMore: 'Learn More',
    readyToStart: 'Ready to Start Your Journey?',
    contactToday: 'Contact us today for a free consultation',
    scheduleConsultation: 'Schedule Consultation',
    viewSuccessStories: 'View Success Stories',
    
    // Application Form
    completeApplication: 'Complete Your Application',
    fillOutAllRequired: 'Please fill out all the required information to submit your application',
    personalInformation: 'Personal Information',
    fullName: 'Full Name',
    nationality: 'Nationality',
    whatsappNumber: 'WhatsApp Number',
    preferredStartDate: 'Preferred Start Date',
    profilePicture: 'Profile Picture',
    academicInformation: 'Academic Information',
    currentEducationLevel: 'Current Education Level',
    selectEducationLevel: 'Select education level',
    highSchool: 'High School',
    bachelorDegree: "Bachelor's Degree",
    masterDegree: "Master's Degree",
    phd: 'PhD',
    fieldOfStudy: 'Field of Study',
    fieldOfStudyPlaceholder: 'e.g., Computer Science, Medicine, Engineering',
    academicGpa: 'Academic GPA',
    gpaPlaceholder: 'e.g., 3.75',
    previousDegree: 'Previous Degree',
    previousDegreePlaceholder: 'e.g., Bachelor of Science in Physics',
    languageOfInstruction: 'Language of Instruction',
    selectLanguage: 'Select language',
    english: 'English',
    french: 'Français',
    arabic: 'العربية',
    localLanguage: 'Local Language',
    englishProficiency: 'English Proficiency',
    selectProficiencyLevel: 'Select proficiency level',
    nativeSpeaker: 'Native Speaker',
    fluent: 'Fluent',
    advanced: 'Advanced',
    intermediate: 'Intermediate',
    beginner: 'Beginner',
    toeflCertified: 'TOEFL Certified',
    ieltsCertified: 'IELTS Certified',
    motivationLetter: 'Motivation Letter',
    motivationLetterPlaceholder: 'Tell us why you want to study in this country and how it aligns with your goals...',
    emergencyContactSupport: 'Emergency Contact & Support',
    emergencyContactName: 'Emergency Contact Name',
    emergencyContactNamePlaceholder: 'Full name of emergency contact',
    emergencyContactPhone: 'Emergency Contact Phone',
    financialSupportNeeded: 'I need financial support for my studies',
    scholarshipInterest: 'I am interested in scholarship opportunities',
    documentsUpload: 'Documents Upload',
    supportingDocuments: 'Supporting Documents',
    documentsDescription: 'Upload academic transcripts, certificates, passport copy, etc. (PDF, DOC, or Image files)',
    uploadingFiles: 'Uploading Files...',
    submittingApplication: 'Submitting Application...',
    submitApplication: 'Submit Application',
    missingInformation: 'Missing Information',
    fillAllRequired: 'Please fill in all required fields.',
    uploadFailed: 'Upload Failed',
    failedToUpload: 'Failed to upload profile picture. Please try again.',
    submissionFailed: 'Submission Failed',
    errorSubmittingApplication: 'There was an error submitting your application. Please try again.',
    applicationSubmittedSuccessfully: 'Application Submitted Successfully!',
    reviewAndContact: "We'll review your application and contact you within 48 hours via WhatsApp.",
    unexpectedError: 'An unexpected error occurred. Please try again.',
    backTo: 'Back to',
    applicationForm: 'Application Form',
  },
  tr: {
    // Navigation
    home: 'Ana Sayfa',
    about: 'Hakkımızda',
    services: 'Hizmetler',
    testimonials: 'Referanslar',
    contact: 'İletişim',
    
    // Auth
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    logout: 'Çıkış Yap',
    email: 'E-posta',
    password: 'Şifre',
    confirmPassword: 'Şifreyi Onayla',
    fullName: 'Ad Soyad',
    phone: 'Telefon',
    
    // Countries
    turkey: 'Türkiye',
    france: 'Fransa',
    tunisia: 'Tunus',
    canada: 'Kanada',
    
    // Services
    universityAdmission: 'Üniversite Kabul',
    scholarships: 'Burslar',
    visaGuidance: 'Vize Rehberliği',
    accommodation: 'Konaklama',
    
    // Contact
    contactTitle: 'İletişime Geçin',
    sendMessage: 'Mesaj Gönder',
    subject: 'Konu',
    message: 'Mesaj',
    sendMessageBtn: 'Mesaj Gönder',
    quickContact: 'Hızlı İletişim',
    chatWhatsApp: 'WhatsApp\'ta Sohbet Et',
    ourOffices: 'Ofislerimiz',
    businessHours: 'Çalışma Saatleri',
    mondayFriday: 'Pazartesi - Cuma',
    saturday: 'Cumartesi',
    sunday: 'Pazar',
    closed: 'Kapalı',
    emergencyConsultations: 'Acil danışmanlık 7/24 mevcuttur',
    available24Hours: '7/24 Müsait',
    
    // About
    aboutDescription: 'Uluslararası eğitimde güvenilir ortağınız, öğrencilerin yurtdışında eğitim alma hayallerini gerçekleştirmelerine yardımcı oluyoruz.',
    
    // Homepage content
    welcomeSubtitle: 'Dünya standartlarında eğitim ve unutulmaz deneyimlerin kapısı. Fırsatları keşfedin, üniversitelerle bağlantı kurun ve uluslararası yolculuğunuza bugün başlayın.',
    startJourney: 'Yolculuğunuza Başlayın',
    getStarted: 'Başlayın',
    universities: 'Üniversiteler',
    internationalStudents: 'Uluslararası Öğrenciler',
    provinces: 'İller',
    seasons: 'Mevsimler',
    everythingAboutTurkey: 'Türkiye Hakkında Her Şey',
    allInformationNeeded: 'Yurtdışı eğitim konusunda bilinçli kararlar vermeniz için ihtiyacınız olan tüm bilgiler',
    universitiesAndPrograms: 'Üniversiteler ve Programlar',
    exploreUniversities: 'En iyi üniversiteleri ve akademik programları keşfedin',
    scholarshipsAndFunding: 'Burslar ve Finansman',
    turkishScholarships: 'Türk hükümeti ve üniversite burslarını keşfedin',
    citiesAndLifestyle: 'Şehirler ve Yaşam Tarzı',
    discoverCities: 'Türk şehirlerini ve öğrenci yaşamını keşfedin',
    economyAndLivingCosts: 'Ekonomi ve Yaşam Maliyetleri',
    currentEconomicSituation: 'Mevcut ekonomik durum ve yaşam maliyeti',
    whyTurkey: 'Neden Türkiye?',
    strategicLocation: 'Stratejik Konum',
    strategicLocationDesc: 'Zengin kültürel miras ile Avrupa ve Asya arasında köprü',
    culturalRichness: 'Kültürel Zenginlik',
    culturalRichnessDesc: 'Çeşitli kültürleri ve tarihi önemi deneyimleyin',
    hospitality: 'Türk Misafirperverliği',
    hospitalityDesc: 'Uluslararası öğrenciler için sıcak karşılama ve dostane ortam',
    easyAccess: 'Kolay Erişim',
    easyAccessDesc: 'Avrupa, Asya ve Afrika\'ya uygun seyahat bağlantıları',
    startEducationalJourney: 'Eğitim Yolculuğunuza Bugün Başlayın',
    guideFromApplication: 'Başvurudan mezuniyete kadar size rehberlik ediyoruz - başarınız bizim misyonumuz',
    applyNow: 'Şimdi Başvur',
    
    // Services descriptions
    universityAdmissionDesc: 'Üniversite başvuruları ve kabul süreci için tam destek.',
    scholarshipsDesc: 'Yurtdışı eğitiminizi finanse etmek için burs bulun ve başvurun.',
    visaGuidanceDesc: 'Vize başvuruları ve belgelendirme konusunda uzman yardımı.',
    accommodationDesc: 'Uygun barınma ve konaklama seçenekleri bulma konusunda yardım.',
    
    // Service features
    universitySelection: 'Üniversite Seçimi',
    applicationDocuments: 'Başvuru Belgeleri',
    personalStatement: 'Kişisel Beyan',
    interviewPrep: 'Mülakat Hazırlığı',
    applicationSubmission: 'Başvuru Gönderimi',
    scholarshipDatabase: 'Burs Veritabanı',
    eligibilityAssessment: 'Uygunluk Değerlendirmesi',
    applicationAssistance: 'Başvuru Yardımı',
    essayWriting: 'Kompozisyon Yazımı',
    financialAid: 'Mali Yardım',
    visaConsultation: 'Vize Danışmanlığı',
    documentChecklist: 'Belge Kontrol Listesi',
    embassyAppointment: 'Büyükelçilik Randevusu',
    postArrival: 'Varış Sonrası Destek',
    universityDorms: 'Üniversite Yurtları',
    privateHousing: 'Özel Konut',
    rentalAgreement: 'Kira Sözleşmesi',
    areaRecommendations: 'Bölge Önerileri',
    moveInSupport: 'Taşınma Desteği',
    
    // Process
    ourProcess: 'Sürecimiz',
    simpleStepByStep: 'Başlamanız için basit adım adım süreç',
    initialConsultation: 'İlk Danışmanlık',
    initialConsultationDesc: 'Hedeflerinizi ve tercihlerinizi anlamak için ücretsiz danışmanlık',
    personalizedPlan: 'Kişiselleştirilmiş Plan',
    personalizedPlanDesc: 'Akademik ve kariyer hedeflerinize göre özel yol haritası',
    applicationSupport: 'Başvuru Desteği',
    applicationSupportDesc: 'Başvurular ve belgelendirme için uçtan uca yardım',
    successBeyond: 'Başarı ve Ötesi',
    successBeyondDesc: 'Yurtdışında eğitiminize başladıktan sonra bile devam eden destek',
    
    // General
    ourServices: 'Hizmetlerimiz',
    comprehensiveSupport: 'Uluslararası eğitim yolculuğunuz için kapsamlı destek',
    learnMore: 'Daha Fazla Bilgi',
    readyToStart: 'Yolculuğunuza Başlamaya Hazır mısınız?',
    contactToday: 'Ücretsiz danışmanlık için bugün bizimle iletişime geçin',
    scheduleConsultation: 'Danışmanlık Planla',
    viewSuccessStories: 'Başarı Hikayelerini Görüntüle',
    
    // Application Form
    completeApplication: 'Başvurunuzu Tamamlayın',
    fillOutAllRequired: 'Başvurunuzu göndermek için gerekli tüm bilgileri doldurun',
    personalInformation: 'Kişisel Bilgiler',
    fullName: 'Ad Soyad',
    nationality: 'Uyruk',
    whatsappNumber: 'WhatsApp Numarası',
    preferredStartDate: 'Tercih Edilen Başlangıç Tarihi',
    profilePicture: 'Profil Resmi',
    academicInformation: 'Akademik Bilgiler',
    currentEducationLevel: 'Mevcut Eğitim Seviyesi',
    selectEducationLevel: 'Eğitim seviyesi seçin',
    highSchool: 'Lise',
    bachelorDegree: 'Lisans Derecesi',
    masterDegree: 'Yüksek Lisans Derecesi',
    phd: 'Doktora',
    fieldOfStudy: 'Çalışma Alanı',
    fieldOfStudyPlaceholder: 'örn., Bilgisayar Bilimleri, Tıp, Mühendislik',
    academicGpa: 'Akademik Not Ortalaması',
    gpaPlaceholder: 'örn., 3.75',
    previousDegree: 'Önceki Derece',
    previousDegreePlaceholder: 'örn., Fizik Lisans Derecesi',
    languageOfInstruction: 'Öğretim Dili',
    selectLanguage: 'Dil seçin',
    english: 'İngilizce',
    french: 'Fransızca',
    arabic: 'Arapça',
    localLanguage: 'Yerel Dil',
    englishProficiency: 'İngilizce Yeterliliği',
    selectProficiencyLevel: 'Yeterlilik seviyesi seçin',
    nativeSpeaker: 'Ana Dil Konuşucusu',
    fluent: 'Akıcı',
    advanced: 'İleri',
    intermediate: 'Orta',
    beginner: 'Başlangıç',
    toeflCertified: 'TOEFL Sertifikalı',
    ieltsCertified: 'IELTS Sertifikalı',
    motivationLetter: 'Motivasyon Mektubu',
    motivationLetterPlaceholder: 'Bu ülkede neden okumak istediğinizi ve hedeflerinizle nasıl uyumlu olduğunu anlatın...',
    emergencyContactSupport: 'Acil Durum İletişim ve Destek',
    emergencyContactName: 'Acil Durum İletişim Adı',
    emergencyContactNamePlaceholder: 'Acil durum iletişim tam adı',
    emergencyContactPhone: 'Acil Durum İletişim Telefonu',
    financialSupportNeeded: 'Çalışmalarım için mali desteğe ihtiyacım var',
    scholarshipInterest: 'Burs fırsatlarıyla ilgileniyorum',
    documentsUpload: 'Belge Yükleme',
    supportingDocuments: 'Destekleyici Belgeler',
    documentsDescription: 'Akademik transkriptler, sertifikalar, pasaport kopyası vb. yükleyin (PDF, DOC veya Resim dosyaları)',
    uploadingFiles: 'Dosyalar Yükleniyor...',
    submittingApplication: 'Başvuru Gönderiliyor...',
    submitApplication: 'Başvuru Gönder',
    missingInformation: 'Eksik Bilgi',
    fillAllRequired: 'Lütfen tüm gerekli alanları doldurun.',
    uploadFailed: 'Yükleme Başarısız',
    failedToUpload: 'Profil resmi yüklenemedi. Lütfen tekrar deneyin.',
    submissionFailed: 'Gönderim Başarısız',
    errorSubmittingApplication: 'Başvurunuzu gönderirken bir hata oluştu. Lütfen tekrar deneyin.',
    applicationSubmittedSuccessfully: 'Başvuru Başarıyla Gönderildi!',
    reviewAndContact: 'Başvurunuzu inceleyeceğiz ve 48 saat içinde WhatsApp üzerinden sizinle iletişime geçeceğiz.',
    unexpectedError: 'Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.',
    backTo: 'Geri dön',
    applicationForm: 'Başvuru Formu',
  },
  fr: {
    // Navigation
    home: 'Accueil',
    about: 'À propos',
    services: 'Services',
    testimonials: 'Témoignages',
    contact: 'Contact',
    
    // Auth
    login: 'Connexion',
    register: 'S\'inscrire',
    logout: 'Déconnexion',
    email: 'E-mail',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    fullName: 'Nom complet',
    phone: 'Téléphone',
    
    // Countries
    turkey: 'Turquie',
    france: 'France',
    tunisia: 'Tunisie',
    canada: 'Canada',
    
    // Services
    universityAdmission: 'Admission Universitaire',
    scholarships: 'Bourses',
    visaGuidance: 'Orientation Visa',
    accommodation: 'Hébergement',
    
    // Contact
    contactTitle: 'Contactez-nous',
    sendMessage: 'Envoyer un message',
    subject: 'Sujet',
    message: 'Message',
    sendMessageBtn: 'Envoyer le message',
    quickContact: 'Contact rapide',
    chatWhatsApp: 'Chatter sur WhatsApp',
    ourOffices: 'Nos bureaux',
    businessHours: 'Heures d\'ouverture',
    mondayFriday: 'Lundi - Vendredi',
    saturday: 'Samedi',
    sunday: 'Dimanche',
    closed: 'Fermé',
    emergencyConsultations: 'Consultations d\'urgence disponibles 24h/24 et 7j/7',
    available24Hours: 'Disponible 24h/24 et 7j/7',
    
    // About
    aboutDescription: 'Votre partenaire de confiance en éducation internationale, aidant les étudiants à réaliser leurs rêves d\'études à l\'étranger.',
    
    // Homepage content
    welcomeSubtitle: 'Votre passerelle vers une éducation de classe mondiale et des expériences inoubliables. Découvrez les opportunités, connectez-vous avec les universités et commencez votre parcours international aujourd\'hui.',
    startJourney: 'Commencez Votre Parcours',
    getStarted: 'Commencer',
    universities: 'Universités',
    internationalStudents: 'Étudiants Internationaux',
    provinces: 'Provinces',
    seasons: 'Saisons',
    everythingAboutTurkey: 'Tout sur la Turquie',
    allInformationNeeded: 'Toutes les informations dont vous avez besoin pour prendre des décisions éclairées sur vos études à l\'étranger',
    universitiesAndPrograms: 'Universités et Programmes',
    exploreUniversities: 'Explorez les meilleures universités et programmes académiques',
    scholarshipsAndFunding: 'Bourses et Financement',
    turkishScholarships: 'Découvrez les bourses du gouvernement turc et des universités',
    citiesAndLifestyle: 'Villes et Mode de Vie',
    discoverCities: 'Découvrez les villes turques et la vie étudiante',
    economyAndLivingCosts: 'Économie et Coûts de la Vie',
    currentEconomicSituation: 'Situation économique actuelle et coût de la vie',
    whyTurkey: 'Pourquoi la Turquie?',
    strategicLocation: 'Emplacement Stratégique',
    strategicLocationDesc: 'Pont entre l\'Europe et l\'Asie avec un riche patrimoine culturel',
    culturalRichness: 'Richesse Culturelle',
    culturalRichnessDesc: 'Découvrez des cultures diverses et une signification historique',
    hospitality: 'Hospitalité Turque',
    hospitalityDesc: 'Accueil chaleureux et environnement convivial pour les étudiants internationaux',
    easyAccess: 'Accès Facile',
    easyAccessDesc: 'Connexions de voyage pratiques vers l\'Europe, l\'Asie et l\'Afrique',
    startEducationalJourney: 'Commencez Votre Parcours Éducatif Aujourd\'hui',
    guideFromApplication: 'Nous vous guidons de la candidature à la graduation - votre succès est notre mission',
    applyNow: 'Postuler Maintenant',
    
    // Services descriptions
    universityAdmissionDesc: 'Support complet pour les candidatures universitaires et le processus d\'admission.',
    scholarshipsDesc: 'Trouvez et postulez pour des bourses pour financer vos études à l\'étranger.',
    visaGuidanceDesc: 'Assistance experte pour les demandes de visa et la documentation.',
    accommodationDesc: 'Aide pour trouver des options de logement et d\'hébergement appropriées.',
    
    // Service features
    universitySelection: 'Sélection d\'université',
    applicationDocuments: 'Documents de candidature',
    personalStatement: 'Déclaration personnelle',
    interviewPrep: 'Préparation d\'entretien',
    applicationSubmission: 'Soumission de candidature',
    scholarshipDatabase: 'Base de données de bourses',
    eligibilityAssessment: 'Évaluation d\'éligibilité',
    applicationAssistance: 'Assistance à la candidature',
    essayWriting: 'Rédaction d\'essai',
    financialAid: 'Aide financière',
    visaConsultation: 'Consultation visa',
    documentChecklist: 'Liste de contrôle des documents',
    embassyAppointment: 'Rendez-vous à l\'ambassade',
    postArrival: 'Support post-arrivée',
    universityDorms: 'Résidences universitaires',
    privateHousing: 'Logement privé',
    rentalAgreement: 'Contrat de location',
    areaRecommendations: 'Recommandations de zone',
    moveInSupport: 'Support d\'emménagement',
    
    // Process
    ourProcess: 'Notre processus',
    simpleStepByStep: 'Processus simple étape par étape pour commencer',
    initialConsultation: 'Consultation initiale',
    initialConsultationDesc: 'Consultation gratuite pour comprendre vos objectifs et préférences',
    personalizedPlan: 'Plan personnalisé',
    personalizedPlanDesc: 'Feuille de route personnalisée adaptée à vos objectifs académiques et professionnels',
    applicationSupport: 'Support de candidature',
    applicationSupportDesc: 'Assistance de bout en bout avec les candidatures et la documentation',
    successBeyond: 'Succès et au-delà',
    successBeyondDesc: 'Support continu même après avoir commencé vos études à l\'étranger',
    
    // General
    ourServices: 'Nos services',
    comprehensiveSupport: 'Support complet pour votre parcours d\'éducation internationale',
    learnMore: 'En savoir plus',
    readyToStart: 'Prêt à commencer votre voyage?',
    contactToday: 'Contactez-nous aujourd\'hui pour une consultation gratuite',
    scheduleConsultation: 'Planifier une consultation',
    viewSuccessStories: 'Voir les histoires de succès',
    
    // Application Form
    completeApplication: 'Complétez Votre Candidature',
    fillOutAllRequired: 'Veuillez remplir toutes les informations requises pour soumettre votre candidature',
    personalInformation: 'Informations Personnelles',
    fullName: 'Nom Complet',
    nationality: 'Nationalité',
    whatsappNumber: 'Numéro WhatsApp',
    preferredStartDate: 'Date de Début Préférée',
    profilePicture: 'Photo de Profil',
    academicInformation: 'Informations Académiques',
    currentEducationLevel: 'Niveau d\'Éducation Actuel',
    selectEducationLevel: 'Sélectionner le niveau d\'éducation',
    highSchool: 'Lycée',
    bachelorDegree: 'Licence',
    masterDegree: 'Master',
    phd: 'Doctorat',
    fieldOfStudy: 'Domaine d\'Étude',
    fieldOfStudyPlaceholder: 'ex., Informatique, Médecine, Ingénierie',
    academicGpa: 'Moyenne Académique',
    gpaPlaceholder: 'ex., 3.75',
    previousDegree: 'Diplôme Précédent',
    previousDegreePlaceholder: 'ex., Licence en Sciences Physiques',
    languageOfInstruction: 'Langue d\'Instruction',
    selectLanguage: 'Sélectionner la langue',
    english: 'Anglais',
    french: 'Français',
    arabic: 'Arabe',
    localLanguage: 'Langue Locale',
    englishProficiency: 'Maîtrise de l\'Anglais',
    selectProficiencyLevel: 'Sélectionner le niveau de maîtrise',
    nativeSpeaker: 'Locuteur Natif',
    fluent: 'Courant',
    advanced: 'Avancé',
    intermediate: 'Intermédiaire',
    beginner: 'Débutant',
    toeflCertified: 'Certifié TOEFL',
    ieltsCertified: 'Certifié IELTS',
    motivationLetter: 'Lettre de Motivation',
    motivationLetterPlaceholder: 'Dites-nous pourquoi vous voulez étudier dans ce pays et comment cela s\'aligne avec vos objectifs...',
    emergencyContactSupport: 'Contact d\'Urgence et Support',
    emergencyContactName: 'Nom du Contact d\'Urgence',
    emergencyContactNamePlaceholder: 'Nom complet du contact d\'urgence',
    emergencyContactPhone: 'Téléphone du Contact d\'Urgence',
    financialSupportNeeded: 'J\'ai besoin d\'un soutien financier pour mes études',
    scholarshipInterest: 'Je suis intéressé par les opportunités de bourses',
    documentsUpload: 'Téléchargement de Documents',
    supportingDocuments: 'Documents de Support',
    documentsDescription: 'Téléchargez les relevés académiques, certificats, copie de passeport, etc. (fichiers PDF, DOC ou Image)',
    uploadingFiles: 'Téléchargement des Fichiers...',
    submittingApplication: 'Soumission de la Candidature...',
    submitApplication: 'Soumettre la Candidature',
    missingInformation: 'Informations Manquantes',
    fillAllRequired: 'Veuillez remplir tous les champs requis.',
    uploadFailed: 'Échec du Téléchargement',
    failedToUpload: 'Échec du téléchargement de la photo de profil. Veuillez réessayer.',
    submissionFailed: 'Échec de la Soumission',
    errorSubmittingApplication: 'Il y a eu une erreur lors de la soumission de votre candidature. Veuillez réessayer.',
    applicationSubmittedSuccessfully: 'Candidature Soumise avec Succès!',
    reviewAndContact: 'Nous examinerons votre candidature et vous contacterons dans les 48 heures via WhatsApp.',
    unexpectedError: 'Une erreur inattendue s\'est produite. Veuillez réessayer.',
    backTo: 'Retour à',
    applicationForm: 'Formulaire de Candidature',
  },
  ar: {
    // Navigation
    home: 'الرئيسية',
    about: 'حولنا',
    services: 'الخدمات',
    testimonials: 'الشهادات',
    contact: 'اتصل بنا',
    
    // Auth
    login: 'تسجيل الدخول',
    register: 'التسجيل',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    fullName: 'الاسم الكامل',
    phone: 'الهاتف',
    
    // Countries
    turkey: 'تركيا',
    france: 'فرنسا',
    tunisia: 'تونس',
    canada: 'كندا',
    
    // Services
    universityAdmission: 'القبول الجامعي',
    scholarships: 'المنح الدراسية',
    visaGuidance: 'إرشادات التأشيرة',
    accommodation: 'الإقامة',
    
    // Contact
    contactTitle: 'اتصل بنا',
    sendMessage: 'إرسال رسالة',
    subject: 'الموضوع',
    message: 'الرسالة',
    sendMessageBtn: 'إرسال الرسالة',
    quickContact: 'اتصال سريع',
    chatWhatsApp: 'دردشة على واتساب',
    ourOffices: 'مكاتبنا',
    businessHours: 'ساعات العمل',
    mondayFriday: 'الاثنين - الجمعة',
    saturday: 'السبت',
    sunday: 'الأحد',
    closed: 'مغلق',
    emergencyConsultations: 'استشارات طارئة متاحة على مدار الساعة',
    available24Hours: 'متاح على مدار الساعة',
    
    // About
    aboutDescription: 'شريكك الموثوق في التعليم الدولي، نساعد الطلاب على تحقيق أحلامهم في الدراسة بالخارج.',
    
    // Homepage content
    welcomeSubtitle: 'بوابتك إلى التعليم العالمي والتجارب التي لا تُنسى. اكتشف الفرص، تواصل مع الجامعات، وابدأ رحلتك الدولية اليوم.',
    startJourney: 'ابدأ رحلتك',
    getStarted: 'البدء',
    universities: 'الجامعات',
    internationalStudents: 'الطلاب الدوليون',
    provinces: 'المحافظات',
    seasons: 'الفصول',
    everythingAboutTurkey: 'كل شيء عن تركيا',
    allInformationNeeded: 'جميع المعلومات التي تحتاجها لاتخاذ قرارات مدروسة حول تعليمك في الخارج',
    universitiesAndPrograms: 'الجامعات والبرامج',
    exploreUniversities: 'استكشف أفضل الجامعات والبرامج الأكاديمية',
    scholarshipsAndFunding: 'المنح الدراسية والتمويل',
    turkishScholarships: 'اكتشف منح الحكومة التركية والجامعات',
    citiesAndLifestyle: 'المدن ونمط الحياة',
    discoverCities: 'اكتشف المدن التركية وحياة الطلاب',
    economyAndLivingCosts: 'الاقتصاد وتكاليف المعيشة',
    currentEconomicSituation: 'الوضع الاقتصادي الحالي وتكلفة المعيشة',
    whyTurkey: 'لماذا تركيا؟',
    strategicLocation: 'الموقع الاستراتيجي',
    strategicLocationDesc: 'جسر بين أوروبا وآسيا مع تراث ثقافي غني',
    culturalRichness: 'الثراء الثقافي',
    culturalRichnessDesc: 'اختبر الثقافات المتنوعة والأهمية التاريخية',
    hospitality: 'الضيافة التركية',
    hospitalityDesc: 'ترحيب حار وبيئة ودية للطلاب الدوليين',
    easyAccess: 'سهولة الوصول',
    easyAccessDesc: 'اتصالات سفر مريحة إلى أوروبا وآسيا وأفريقيا',
    startEducationalJourney: 'ابدأ رحلتك التعليمية اليوم',
    guideFromApplication: 'نحن نرشدك من التطبيق إلى التخرج - نجاحك هو مهمتنا',
    applyNow: 'تقدم الآن',
    
    // Services descriptions
    universityAdmissionDesc: 'دعم كامل لطلبات الجامعة وعملية القبول.',
    scholarshipsDesc: 'ابحث وتقدم للحصول على منح دراسية لتمويل تعليمك في الخارج.',
    visaGuidanceDesc: 'مساعدة خبراء في طلبات التأشيرة والوثائق.',
    accommodationDesc: 'مساعدة في العثور على خيارات السكن والإقامة المناسبة.',
    
    // Service features
    universitySelection: 'اختيار الجامعة',
    applicationDocuments: 'وثائق التطبيق',
    personalStatement: 'البيان الشخصي',
    interviewPrep: 'إعداد المقابلة',
    applicationSubmission: 'تقديم الطلب',
    scholarshipDatabase: 'قاعدة بيانات المنح الدراسية',
    eligibilityAssessment: 'تقييم الأهلية',
    applicationAssistance: 'مساعدة التطبيق',
    essayWriting: 'كتابة المقال',
    financialAid: 'المساعدة المالية',
    visaConsultation: 'استشارة التأشيرة',
    documentChecklist: 'قائمة مراجعة الوثائق',
    embassyAppointment: 'موعد السفارة',
    postArrival: 'دعم ما بعد الوصول',
    universityDorms: 'مساكن الجامعة',
    privateHousing: 'السكن الخاص',
    rentalAgreement: 'اتفاقية الإيجار',
    areaRecommendations: 'توصيات المنطقة',
    moveInSupport: 'دعم الانتقال',
    
    // Process
    ourProcess: 'عمليتنا',
    simpleStepByStep: 'عملية بسيطة خطوة بخطوة للبدء',
    initialConsultation: 'الاستشارة الأولية',
    initialConsultationDesc: 'استشارة مجانية لفهم أهدافك وتفضيلاتك',
    personalizedPlan: 'خطة مخصصة',
    personalizedPlanDesc: 'خارطة طريق مخصصة مصممة خصيصًا لأهدافك الأكاديمية والمهنية',
    applicationSupport: 'دعم التطبيق',
    applicationSupportDesc: 'مساعدة شاملة مع التطبيقات والوثائق',
    successBeyond: 'النجاح وما بعده',
    successBeyondDesc: 'دعم مستمر حتى بعد بدء دراستك في الخارج',
    
    // General
    ourServices: 'خدماتنا',
    comprehensiveSupport: 'دعم شامل لرحلة تعليمك الدولي',
    learnMore: 'اعرف أكثر',
    readyToStart: 'هل أنت مستعد لبدء رحلتك؟',
    contactToday: 'اتصل بنا اليوم للحصول على استشارة مجانية',
    scheduleConsultation: 'جدولة استشارة',
    viewSuccessStories: 'عرض قصص النجاح',
    
    // Application Form
    completeApplication: 'أكمل طلب التقديم الخاص بك',
    fillOutAllRequired: 'يرجى ملء جميع المعلومات المطلوبة لتقديم طلبك',
    personalInformation: 'المعلومات الشخصية',
    fullName: 'الاسم الكامل',
    nationality: 'الجنسية',
    whatsappNumber: 'رقم الواتساب',
    preferredStartDate: 'تاريخ البدء المفضل',
    profilePicture: 'الصورة الشخصية',
    academicInformation: 'المعلومات الأكاديمية',
    currentEducationLevel: 'المستوى التعليمي الحالي',
    selectEducationLevel: 'اختر المستوى التعليمي',
    highSchool: 'الثانوية العامة',
    bachelorDegree: 'درجة البكالوريوس',
    masterDegree: 'درجة الماجستير',
    phd: 'درجة الدكتوراه',
    fieldOfStudy: 'مجال الدراسة',
    fieldOfStudyPlaceholder: 'مثال: علوم الحاسوب، الطب، الهندسة',
    academicGpa: 'المعدل الأكاديمي',
    gpaPlaceholder: 'مثال: 3.75',
    previousDegree: 'الدرجة السابقة',
    previousDegreePlaceholder: 'مثال: بكالوريوس في علوم الفيزياء',
    languageOfInstruction: 'لغة التدريس',
    selectLanguage: 'اختر اللغة',
    english: 'الإنجليزية',
    french: 'الفرنسية',
    arabic: 'العربية',
    localLanguage: 'اللغة المحلية',
    englishProficiency: 'إتقان اللغة الإنجليزية',
    selectProficiencyLevel: 'اختر مستوى الإتقان',
    nativeSpeaker: 'متحدث أصلي',
    fluent: 'طلق',
    advanced: 'متقدم',
    intermediate: 'متوسط',
    beginner: 'مبتدئ',
    toeflCertified: 'معتمد TOEFL',
    ieltsCertified: 'معتمد IELTS',
    motivationLetter: 'خطاب الدافع',
    motivationLetterPlaceholder: 'أخبرنا لماذا تريد الدراسة في هذا البلد وكيف يتماشى ذلك مع أهدافك...',
    emergencyContactSupport: 'جهة الاتصال للطوارئ والدعم',
    emergencyContactName: 'اسم جهة الاتصال للطوارئ',
    emergencyContactNamePlaceholder: 'الاسم الكامل لجهة الاتصال للطوارئ',
    emergencyContactPhone: 'هاتف جهة الاتصال للطوارئ',
    financialSupportNeeded: 'أحتاج إلى دعم مالي لدراستي',
    scholarshipInterest: 'أنا مهتم بفرص المنح الدراسية',
    documentsUpload: 'تحميل الوثائق',
    supportingDocuments: 'الوثائق الداعمة',
    documentsDescription: 'ارفع الكشوف الأكاديمية والشهادات ونسخة من جواز السفر وغيرها (ملفات PDF أو DOC أو الصور)',
    uploadingFiles: 'جارٍ تحميل الملفات...',
    submittingApplication: 'جارٍ تقديم الطلب...',
    submitApplication: 'تقديم الطلب',
    missingInformation: 'معلومات مفقودة',
    fillAllRequired: 'يرجى ملء جميع الحقول المطلوبة.',
    uploadFailed: 'فشل التحميل',
    failedToUpload: 'فشل في تحميل الصورة الشخصية. يرجى المحاولة مرة أخرى.',
    submissionFailed: 'فشل في التقديم',
    errorSubmittingApplication: 'حدث خطأ أثناء تقديم طلبك. يرجى المحاولة مرة أخرى.',
    applicationSubmittedSuccessfully: 'تم تقديم الطلب بنجاح!',
    reviewAndContact: 'سنراجع طلبك ونتواصل معك خلال 48 ساعة عبر الواتساب.',
    unexpectedError: 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
    backTo: 'العودة إلى',
    applicationForm: 'نموذج التقديم',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
