// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpofoeezjidvfcmebwaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwb2ZvZWV6amlkdmZjbWVid2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTA0NTUsImV4cCI6MjA2NDM4NjQ1NX0.KtDRLlRCFhnog6D4uvuFVk4JboG_kkDi1hFO-_4uwEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);